"""all

Revision ID: a91a948e4fba
Revises: 
Create Date: 2025-10-19 13:57:46.680349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91a948e4fba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_debt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remaining_debt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('outstanding_advance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('total_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('salary_deduction', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('debt_deduction', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rent_deduction', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('milk_deduction', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_advances', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_distributable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('felix_substitute', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_advance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('advance_date', sa.Date(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=80), nullable=False),
    sa.Column('share_ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gross_share', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('advance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_payout', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paid_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_item')
    op.drop_table('weekly_advance')
    op.drop_table('transaction')
    op.drop_table('settlement')
    op.drop_table('notification')
    op.drop_table('user')
    op.drop_table('member')
    op.drop_table('debt')
    # ### end Alembic commands ###
